#!/usr/bin/env python3
"""
YouTube → Vietnamese Summary → Gmail Workflow
One-command execution of the complete pipeline.
"""

import os
import sys
import argparse
import base64
from email.message import EmailMessage
from dotenv import load_dotenv

# Import our existing functions
from summarize_youtube import get_transcript, summarize_transcript
from send_email import get_credentials, send_message

from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

load_dotenv()

def create_email_body(video_data: dict, summary: str, lang: str = "vi") -> str:
    """Format summary as email body."""

    if lang == "vi":
        body = f"""📺 TÓM TẮT VIDEO YOUTUBE

Video: {video_data['title']}
Link: {video_data['url']}

---

{summary}

---

🤖 Được tạo tự động bởi Anti-Gravity DO Framework
Powered by Apify + Azure OpenAI GPT-4o
"""
    else:
        body = f"""📺 YOUTUBE VIDEO SUMMARY

Video: {video_data['title']}
Link: {video_data['url']}

---

{summary}

---

🤖 Auto-generated by Anti-Gravity DO Framework
Powered by Apify + Azure OpenAI GPT-4o
"""

    return body

def create_message(to: str, subject: str, body: str) -> dict:
    """Create an email message."""
    message = EmailMessage()
    message.set_content(body)
    message['To'] = to
    message['Subject'] = subject

    # Encode the message
    encoded_message = base64.urlsafe_b64encode(message.as_bytes()).decode()
    return {'raw': encoded_message}

def main():
    parser = argparse.ArgumentParser(
        description='YouTube → Vietnamese Summary → Email (Complete Workflow)'
    )
    parser.add_argument('--url', required=True, help='YouTube video URL')
    parser.add_argument('--to', help='Recipient email (default: from .env GMAIL_USER)')
    parser.add_argument('--lang', default='vi', choices=['en', 'vi'], help='Summary language (default: vi)')
    parser.add_argument('--mode', choices=['draft', 'send'], default='send', help='Email mode: draft or send (default: send)')

    args = parser.parse_args()

    # Default recipient to self
    recipient = args.to or os.getenv('GMAIL_USER', 'giabaongb0305@gmail.com')

    print("="*60)
    print("🚀 YOUTUBE → SUMMARY → EMAIL WORKFLOW")
    print("="*60 + "\n")

    # Step 1: Get transcript
    print("Step 1/3: Extracting transcript...")
    video_data = get_transcript(args.url)

    if not video_data['transcript']:
        print("❌ Failed to get transcript. Aborting.")
        return

    print(f"✓ Transcript extracted: {len(video_data['transcript'])} characters\n")

    # Step 2: Summarize
    print("Step 2/3: Generating summary...")
    result = summarize_transcript(
        video_data['transcript'],
        lang=args.lang,
        video_title=video_data['title']
    )

    if not result['summary']:
        print("❌ Failed to generate summary. Aborting.")
        return

    print(f"✓ Summary generated: {len(result['summary'])} characters\n")

    # Step 3: Send email
    print("Step 3/3: Sending email...")

    # Create email subject
    if args.lang == "vi":
        subject = f"📺 Tóm tắt Video YouTube - {result['title']}"
    else:
        subject = f"📺 YouTube Video Summary - {result['title']}"

    # Create email body
    body = create_email_body(video_data, result['summary'], args.lang)

    # Authenticate and send
    try:
        creds = get_credentials()
        service = build('gmail', 'v1', credentials=creds)
        message = create_message(recipient, subject, body)

        if args.mode == 'draft':
            draft = service.users().drafts().create(userId='me', body={'message': message}).execute()
            print(f"✅ Draft created: {draft['id']}")
        else:
            msg = send_message(service, 'me', message)
            if msg:
                print(f"✅ Email sent to: {recipient}")
            else:
                print("❌ Failed to send email")
                return

    except HttpError as error:
        print(f"❌ Gmail API error: {error}")
        return

    # Final summary
    print("\n" + "="*60)
    print("✅ WORKFLOW COMPLETE")
    print("="*60)
    print(f"Video: {result['title']}")
    print(f"Language: {args.lang.upper()}")
    print(f"Recipient: {recipient}")
    print(f"Mode: {args.mode.upper()}")
    print("="*60 + "\n")

if __name__ == '__main__':
    main()